"""empty message

Revision ID: 560fe4cb21a5
Revises: 
Create Date: 2023-05-29 10:19:19.497443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560fe4cb21a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_column('ability')

    # ### end Alembic commands ###
