"""empty message

Revision ID: 5cb88679d504
Revises: 
Create Date: 2023-05-23 15:19:57.651169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb88679d504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hero_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hero_name'))

    op.drop_table('hero')
    # ### end Alembic commands ###
